var p1 = [
    { eng: 'pratham tula vandito ganapati ganesh', hin: 'प्रथम तुला वंदितो', dir: '1', id: '3.1' },
  { eng: 'sangeet satyanarayan', hin: 'मोरे घर चलो गणराज', dir: '1', id: '3.2' },
 { eng: 'aal aal re mhatar pan aal re', hin: 'वादळाच्या उंच लाटा जाऊ दे', dir: '1', id: '4.1' },
 { eng: 'pavman pavman jagad prana', hin: 'जय गणराया जय गणराया', dir: '1', id: '4.2' },
 { eng: 'malhari mhalasakant', hin: 'तूच सुर ठावा मजसी', dir: '1', id: '5.1' },
 { eng: 'kab loge hamari khabariya o bajrangbali', hin: 'गजानना श्री गणराया आधि वंदू.', dir: '1', id: '5.2' },
 { eng: 'kabhi ram ban ke kabhi shyam ban ke', hin: 'सुख शांतीचे जीवन जावो', dir: '1', id: '6.1' },
 { eng: 'tumhi ho mata pita tumhi ho', hin: 'विश्व शक्ती विश्व रूपा ..', dir: '1', id: '6.2' },
 { eng: 'shri ram svaye shriram prabhu aikati', hin: 'गणराज पायी मन जड जड जड', dir: '1', id: '7.1' },
 { eng: 'venkatesh dwar tere aaye hai', hin: 'तुज मागतो मी आता', dir: '1', id: '7.2' },
 { eng: 'ram ka gun gan kariye', hin: 'गणपतीच्या दर्शनाने धन्य होऊ या', dir: '1', id: '8.1' },
 { eng: 'jag me sundar hai do nam', hin: 'सा रे ग म प ऽपधनी सां ऽऽऽ', dir: '1', id: '9.1' },
 { eng: 'kuthe shodhishi rameshwar an kuthe shodhishi kashi', hin: 'बाल भक्ता लागी तूची आसरा..', dir: '1', id: '9.2' },
 { eng: 'ai malik tere bande hum, aise ho hamare karam', hin: 'पूर्ण ब्रह्म हे कैवल्याचे', dir: '1', id: '10.1' },
 { eng: 'dev pavalay dev maja malhari', hin: 'स्मरा हो प्रथम गणपतीला', dir: '1', id: '10.2' },
 { eng: 'jay shiv shankar jay shankar bhole', hin: 'वंदन तुजला श्री गणराया ...', dir: '1', id: '11.1' },
 { eng: 'kabhi-kabhi bhagwan ko bhi, bhakton se kam pade', hin: 'गणनायकाय गणदेवताय गणाध्यक्षाय धीमहि', dir: '1', id: '12.1' },
 { eng: 'man tript zhale aahe tujya darshani', hin: 'अबीर गुलाल उधळीत रंग', dir: '1', id: '13.1' },
 { eng: 'maili chadar odhke kaise dwar tihare aavu', hin: 'आणिक दुसरे मज नाही आता', dir: '1', id: '13.2' },
 { eng: 'jo bhaje hari ko sada', hin: 'सदा माझे डोळा जडो तुझी मूर्ति', dir: '1', id: '13.3' },
 { eng: 'kay tula apvi prabhu mi', hin: 'घेई घेई माझे वाचे....', dir: '1', id: '14.1' },
 { eng: 'shodhisi manava rauli mandiri', hin: 'पंढरीच्या लोका किती मारु हांका', dir: '1', id: '14.2' },
 { eng: 'payoji maine ram ratan dhan payo', hin: 'कोण दिवस येईल कैसा', dir: '1', id: '14.3' },
 { eng: 'bhatji bapu raya bhetoniya jave', hin: 'व्रतामाजी व्रत एकादशी पावन', dir: '1', id: '14.4' },
 { eng: 'mai more nayan base raghubir', hin: 'किती पाहू तुझी वाट', dir: '1', id: '15.1' },
 { eng: 'he anjanychya suta tula ramache vardan', hin: 'हेची थोर भक्ति आवडते देवा', dir: '1', id: '15.2' },
 { eng: 'kalyan kari ramraya - janahit vivari', hin: 'आता तरी पुढे हाची उपदेश', dir: '1', id: '15.3' },
 { eng: 'bandh vimochan ram maja', hin: 'धरा बळकट भाव', dir: '1', id: '15.4' },
 { eng: 'ram gava ram ghya ram jivicha visava', hin: 'एक तत्व नामे दृढ धरी मना', dir: '1', id: '16.1' },
 { eng: 'sundar te dhyan shobhe sinhasani', hin: 'सखा दीन वत्सल पंढरीराय', dir: '1', id: '16.2' },
 { eng: 'shriramchandra krupalu bhajman haran bhavmay darunam', hin: 'देवाचिये द्वारी उभा क्षणभरी', dir: '1', id: '16.3' },
 { eng: 'mohe lagi latak, guru charanan ki', hin: 'माझा भाव तुझे चरणी', dir: '1', id: '16.4' },
 { eng: 'asa kasa bai majha bhola shankar', hin: 'निष्ठावंत भाव भक्तांचा स्वधर्म', dir: '1', id: '17.1' },
 { eng: 'jay gange bhagirathi har gange bhagirathi', hin: 'लहान पण देगा देवा', dir: '1', id: '17.2' },
 { eng: 'kashasathi yevu deva tujya mandirat', hin: 'आता कोठे धांवे मन', dir: '1', id: '17.3' },
 { eng: 'kuni sanga ho kanha hirmusla', hin: 'संताचिये गांवी प्रेमाचा सुकाळ', dir: '1', id: '17.4' },
 { eng: 'o aali paha madhur tan', hin: 'माझे माहेर पंढरी.', dir: '1', id: '18.1' },
 { eng: 'chavat krishna radha bholi la', hin: 'धन्य आजि दिन संत दर्शनाचा', dir: '1', id: '18.2' },
 { eng: 'aali dahi wali dahi ghya taji', hin: 'तिर्थ विठ्ठल क्षेत्र विठ्ठल', dir: '1', id: '18.3' },
 { eng: 'aisi lagi lagan mira ho gayi magan', hin: 'हे पंढरी नाथ देवा आम्ही तुला स्मरावे', dir: '1', id: '19.1' },
 { eng: 'vrindavni venu venu vrindavni venu', hin: 'मनी नाही भाव म्हणे देवा मला पाव रे', dir: '1', id: '19.2' },
 { eng: 'keshava madhava tujya namat re godva', hin: 'वेढा वेढा रे पंढरी', dir: '1', id: '20.1' },
 { eng: 'mohana jara thambana thamb re maru nako pichkari', hin: 'आम्ही बिघडलो तुम्ही बिघडाना', dir: '1', id: '20.2' },
 { eng: 'soduni gopila gopila dev mathuresi chalala', hin: 'धरीला पंढरीचा चोर..', dir: '1', id: '20.3' },
 { eng: 'hari nam bhaja ho prabhunam', hin: 'इंद्रायणी काठी देवाची आळंदी', dir: '1', id: '21.1' },
 { eng: 'rutla payi kanta ya advata', hin: 'पंढरी निवासा सख्या पांडुरंगा', dir: '1', id: '21.2' },
 { eng: 'ala ho kanha ala', hin: 'येते पंढरीला तुझ्या सारंगधरा', dir: '1', id: '21.3' },
 { eng: 'yashodecha kanha gokulcha chor', hin: 'पंढरीचा वास चंद्रभागे स्नान', dir: '1', id: '22.1' },
 { eng: 'kadhi karito g chori kadhi kari shirjori', hin: 'दर्शन दे रे देरे भगवंता', dir: '1', id: '22.2' },
 { eng: 'bal zhokyamadhye khele g radha mavshichya ghari', hin: 'चला जाऊ या पंढरपुराला', dir: '1', id: '22.3' },
 { eng: 'advu naka baya advu naka', hin: 'या सुखा कारणे देव वेडावला', dir: '1', id: '23.1' },
 { eng: 'bandano govinda chanddi ananda', hin: 'तुकोबाची अमृतवाणी', dir: '1', id: '23.2' },
 { eng: 'sang sudama haricha chendu', hin: 'तुकोबाची कांता सांगे सांगे लोकापाशी', dir: '1', id: '24.1' },
 { eng: 'murli tuji god kanha', hin: 'चंद्रभागेच्या तीरी उभा मंदीरी', dir: '1', id: '24.2' },
 { eng: 'ka g radhe smit hasli', hin: 'विठु माझा लेकुरवाळा', dir: '1', id: '25.1' },
 { eng: 'chavat kanha bholi radha', hin: 'खेळ मांडीयेला वाळवंटी घाई', dir: '1', id: '25.2' },
 { eng: 'ushir zala ka paratnyala', hin: 'उंचनिच काही नेणे भगवंत', dir: '1', id: '25.3' },
 { eng: 'vajvito pava to krishna murari', hin: 'कांदा मुळा भाजी.', dir: '1', id: '26.1' },
 { eng: 'bhiti bhiti bhiti bai bai bhiti', hin: 'सांगा मी काय करु', dir: '1', id: '26.2' },
 { eng: 'lahan lahan mule gheuni', hin: 'झाला महार पंढरीनाथ', dir: '1', id: '26.3' },
 { eng: 'ghongadiwala kambliwala', hin: 'चला पंढरपुराला जाऊया', dir: '1', id: '27.1' },
 { eng: 'are kanha ya gavlani tula ghabarti', hin: 'जातो माघारी पंढरी नाथा.', dir: '1', id: '27.2' },
 { eng: 'khal yashvade krishnan lonni', hin: 'सांडोनीया सर्व आशा संसाराची', dir: '1', id: '28.1' },
 { eng: 'yashvade g bal tujha g', hin: 'बा रे पांडूरंगा केंव्हा भेट देसी', dir: '1', id: '28.2' },
 { eng: 'nako zhombu padarala', hin: 'आगा पंढरीच्या राया....', dir: '1', id: '28.3' },
 { eng: 'tuji sangati nahi kamachi', hin: 'संताचिये गावी प्रेमाचा सुकाळ', dir: '1', id: '29.1' },
 { eng: 'ala kanha magnyasi ala', hin: 'कैवल्याचा चांदण्याला भुकेला चकोर', dir: '1', id: '29.2' },
 { eng: 'dhaka madhla mohan maja', hin: 'विठ्ठलाच्या पायी वीट झाली भाग्यवंत', dir: '1', id: '30.1' },
 { eng: 'mala advu nako re giridhari', hin: 'जय पांडुरंग ऽऽ प्रभो विठ्ठला', dir: '1', id: '30.2' },
 { eng: 'ala re bai bai ala re bai bai ala re', hin: 'विठ्ठल - विठ्ठल स्मरे वेळो वेळा', dir: '1', id: '31.1' },
 { eng: 'davya gudghyane rangto', hin: 'जाणं कशाला दूर मजला इथचं पंढरपूर', dir: '1', id: '31.2' },
 { eng: 'kunj vanachi wat radhike kunj vanachi wat', hin: 'उदंड देखिले, उदंड ऐकीले', dir: '1', id: '32.1' },
 { eng: 'wakuni tak sada g radhe', hin: 'काया ही पंढरी आत्मा हा विठल आवडीने भावे हरी नाम घेसी', dir: '1', id: '32.2' },
 { eng: 'kiti god murlichy nadane', hin: 'आवडीने भावे हरी नाम घेसी', dir: '1', id: '33.1' },
 { eng: 'wariyane kundal hale', hin: 'वाहे चंद्रभागा तुका दंग भजनात', dir: '1', id: '33.2' },
 { eng: 'asa kasa devacha dev bai thakda', hin: 'टाळ बोले चिपळीला ..', dir: '1', id: '34.1' },
 { eng: 'godhne charavaya jato sarangapani', hin: 'येग येग विठाबाई', dir: '1', id: '34.2' },
 { eng: 'jau de re mala, jau de re mala', hin: 'आली कुठूनशी कानी टाळ मृदुंगाचि धून', dir: '1', id: '35.1' },
 { eng: 'malaygiricha chandan gandhit dhup tula davila', hin: 'फिरत्या चाका वरती देसी..', dir: '1', id: '35.2' },
 { eng: 'nesli g bai chandrkala thipkyachi', hin: 'जन्मो जन्मी आम्ही बहु पुण्य केले', dir: '1', id: '36.1' },
 { eng: 'ghuslit hote dari mi loni', hin: 'देवाचिये द्वारी उभा क्षणभरी', dir: '1', id: '36.2' },
 { eng: 'krishna majkade pahoo nako', hin: 'देव माझा विठू सावळा..', dir: '1', id: '37.1' },
 { eng: 'krishna tula mi takid karte', hin: 'कानडा राजा पंढरीचा', dir: '1', id: '37.2' },
 { eng: 'kanhaiya rutali re ghongadi', hin: 'अवघे गर्जे पंढरपूर', dir: '1', id: '38.1' },
 { eng: 'tore bansi ke nad diwani bhai', hin: 'चरणी वाहे चंद्रभागा युगे अठावीस उभा', dir: '1', id: '38.2' },
 { eng: 'mohan pyare ko tune na jana re', hin: 'चला जाऊया राममंदीराला', dir: '1', id: '39.1' },
 { eng: 'tumbin mori kaun khabar le', hin: 'विठ्ठल टाळ विठ्ठल दिंडी', dir: '1', id: '40.1' },
 { eng: 'mangal karti aayi hai maiya, mangal karya karegi maiya,', hin: 'देहाची तिजोरी भक्तीचाच ठेवा', dir: '1', id: '40.2' },
 { eng: 'harivi sadi g shome majhya aaila', hin: 'पाहु द्या मला - पाहु द्या मला', dir: '1', id: '41.1' },
 { eng: 'mai balak tu mata sherawaliye', hin: 'देव माझे मन लागे तुझे चरणी', dir: '1', id: '41.2' },
 { eng: 'tera sahara ambe ma mujhe tera sahara', hin: 'मज संताचा आधार', dir: '1', id: '42.1' },
 { eng: 'udo udo udo mauli ambabai', hin: 'रुक्माईच्या कांता आता तुझाच रे आसरा', dir: '1', id: '42.2' },
 { eng: 'jago he jagdambe jago he jwala', hin: 'माऊली माऊली.... रूप तुझे', dir: '1', id: '43.1' },
 { eng: 'yaha vaha jaha taha', hin: 'निघालो घेऊन दिंडी विठ्ठलाची', dir: '1', id: '44.1' },
 { eng: 'bhagyad lakshmi baramma', hin: 'दत्तासी गाईन - दत्तासी पाहीन', dir: '1', id: '45.1' },
 { eng: 'shardechya mandiri vine cha zhankar', hin: 'तीन शिरे सहा हात.', dir: '1', id: '45.2' },
 { eng: 'jay ambe, jay durge, mahakali', hin: 'भस्म सुशोभित कोमल काया', dir: '1', id: '45.3' },
 { eng: 'basar vasini maje aai', hin: 'जिथे भक्तिचे गायन चाले', dir: '1', id: '46.1' },
 { eng: 'haldivari kunku shobhe ambabaila', hin: 'दत्त दया घन रे...', dir: '1', id: '46.2' },
 { eng: 'navwari sadi nesun', hin: 'भीमा अमरजा संगमातीरी', dir: '1', id: '46.3' },
 { eng: 'kali kali amavas ki rat me', hin: 'ब्रह्मा विष्णू आणि महेश्वर सामोरी बसले', dir: '1', id: '47.1' },
 { eng: 'udo bola udo', hin: 'नका विचारु देव कसा', dir: '1', id: '47.2' },
 { eng: 'ude ga ambe ude, ude ga ambe ude', hin: 'भान हरपले दत्तप्रभूचे', dir: '1', id: '48.1' },
 { eng: 'mai meri o mai meri, sunle tu binti hamari', hin: 'चला जाऊ या गाणगापुराला', dir: '1', id: '48.2' },
 { eng: 'ambe tujhya darshanachi mala zali ghai', hin: 'निघालो घेऊन दत्ताची पालखी', dir: '1', id: '49.1' },
 { eng: 'karu ya udo udo udo ambabaicha', hin: 'श्रीपाद वल्लभ दिगंबरा नामासाठी त्वरा करा', dir: '1', id: '49.2' },
 { eng: 'lallati bhandar', hin: 'प्रभुविण कोण कुणाचा वाली', dir: '1', id: '50.1' },
 { eng: 'bhaktokon darshan de gayi re', hin: 'माझे पुण्य फळा आले', dir: '1', id: '50.2' },
 { eng: 'ude ude ga ambabai - mazi tuljapurchi aai', hin: 'दिगंबरा दिगंबरा ... धांवत येसी भक्तासाठी', dir: '1', id: '51.1' },
 { eng: 'mi tuza bhutya khara', hin: 'श्रीधरा गुरुवरा - पाव मज पामरा', dir: '1', id: '51.2' },
 { eng: 'adishaktiche kautuk mothe', hin: 'श्रीपाद श्रीवल्लभ नरहरि तारी तारी मजला', dir: '1', id: '52.1' },
 { eng: 'pav mate aai jagdambe', hin: 'सद्गुरु वांचोनि सांपडेना सोय', dir: '1', id: '52.2' },
 { eng: 'bhakticha ladu lavuni', hin: 'सद्गुरु सारिखा असता पाठीराखा...', dir: '1', id: '52.3' },
 { eng: 'bola jagdambe bola', hin: 'गुरुनामाची ओढ दत्तनामाची ओढ', dir: '1', id: '53.1' },
 { eng: 'sunti hai maiya sabki pukar', hin: 'गेला दत्त कुण्या गांवा', dir: '1', id: '53.2' },
 { eng: 'jay jay he jagdambe mata', hin: 'सद्गुरु यावे मम भजनी सादर व्हावे', dir: '1', id: '54.1' },
 { eng: 'ayi sher pe savar maiya odhe chunari', hin: 'गुरुवीण नाही कोणी रे', dir: '1', id: '54.2' },
 { eng: 'tune mujhe bulaya shera waliya', hin: 'अलख निरंजन अलख तू भज ले', dir: '1', id: '55.1' },
 { eng: 'aisa pyar baha do maiya', hin: 'किती सुख आहा, किती सुख है.', dir: '1', id: '55.2' },
 { eng: 'ambe maiya ambe maiya man ja', hin: 'गुरुजीने मज बोलणे खुंटविले', dir: '1', id: '56.1' },
 { eng: 'magto mode bhakticha (jogva)', hin: 'दत्ता ब्रह्मचारी रे ब्रह्मचारी', dir: '1', id: '56.2' },
 { eng: 'anadi nirgun pragatli bhavani (jogva)', hin: 'झालो आम्ही बहु धन्य रे', dir: '1', id: '57.1' },
 { eng: 'bhavtarini mata janani', hin: 'दिवाना आपको नहीं धुंडा', dir: '1', id: '57.2' },
 { eng: 'ambe maiya par karo mori naiyya', hin: 'शिरडी पंढरपुर माझे', dir: '1', id: '57.3' },
 { eng: 'ya ho ya ho ya ho . parvani hi sadhu ya', hin: 'हरिद्वार मथुरा काशी', dir: '1', id: '58.1' },
 { eng: 'chala jau kolhapuri amba darshanala', hin: 'ॐकार स्वरुपा सद्गुरु समर्था', dir: '1', id: '58.2' },
 { eng: 'kulswamini durgamata sinharudh basli', hin: 'रस्त्यावर हे मंदीर', dir: '1', id: '59.1' },
 { eng: 'din hank aikuni prem datle mani', hin: 'कपाळी चंदनाचा टिळा', dir: '1', id: '59.2' },
 { eng: 'shodhu kuthe tujla bhavani', hin: 'अवघे गरजे औदुंबर', dir: '1', id: '60.1' },
 { eng: 'chala jau ya tuljapurala', hin: 'गुरुदत्त दिगंबर भजो रे दिगंबर.', dir: '1', id: '60.2' },
 { eng: 'kiti ant pahasi mate jiv ha bhukela', hin: 'चला चला जाऊ शिरडिला', dir: '1', id: '60.3' },
 { eng: 'pahu dya mala pahu dya mala', hin: 'भक्तांना लळा लावुनी दत्त राहीले गाणगापुरी', dir: '1', id: '61.1' },
 { eng: 'ambe tuje g darshan ghet', hin: 'ऐसा दयाळु ऐसा कृपाळु ..', dir: '1', id: '61.2' },
 { eng: 'karuya jay jaykar', hin: 'एकची ध्यास लागला मनी', dir: '1', id: '62.1' },
 { eng: 'navratricha utsav ala', hin: 'दत्त दत्त दत्त दत्त, दत्त म्हणा', dir: '1', id: '62.2' },
 { eng: 'krupa drushti pahe majla tun aai', hin: 'शिरडीवाले साईबाबा, आया है तेरे दर पे सवाली', dir: '1', id: '63.1' },
 { eng: 'mi lekaru tun may renuke', hin: 'पाऊले चालती काशीम पुरची वाट', dir: '1', id: '64.1' },
 { eng: 'amhi chuklo zari tari kahi', hin: 'स्मरा स्मरा हो दत्त गुरू भवताप हरू', dir: '1', id: '64.2' },
 { eng: 'pav ga tuljapur mate', hin: 'नमन माझे गुरुराया', dir: '1', id: '65.1' },
 { eng: 'rup sundar sundar', hin: 'आता जाऊ चला आम्ही पाहु चला', dir: '1', id: '65.2' },
 { eng: 'pav renuke bhavbhay harini', hin: 'मन लागा मोरा अवधूता से', dir: '1', id: '66.1' },
 { eng: 'ambe tujhya bhetisathi', hin: 'करुणाकर दीन वत्सल दत्ता', dir: '1', id: '66.2' },
 { eng: 'pahuni alis majhya ghari', hin: 'धरियले गे माय, श्रीगुरुचे पाय', dir: '1', id: '66.3' },
 { eng: 'mazi renuka mauli', hin: 'मन तरपत हरी दरशन को आज', dir: '1', id: '67.1' },
 { eng: 'mazi laj tula jagdambe ambe', hin: 'मन लागो रे लागो रे', dir: '1', id: '67.2' },
 { eng: 'jay jay shri shubh mangal varde ambe jagdambe', hin: 'नाम लेने से तर जायेगा', dir: '1', id: '68.1' },
 { eng: 'shirdi wale sai baba aya hun tere dwarka mai', hin: 'शिरडी वाले साई बाबा आया हूँ तेरे द्वारका माई', dir: '1', id: '68.2' },
 { eng: 'nam lene se tar jayega', hin: 'जय जय श्री शुभ मंगल वरदे अंबे जगदंबे', dir: '1', id: '69.1' },
 { eng: 'man lago re lago re', hin: 'माझी लाज तुला जगदंबे अंबे', dir: '1', id: '69.2' },
 { eng: 'man tarpat hari darshan ko aaj', hin: 'माझी रेणुका माऊली', dir: '1', id: '70.1' },
 { eng: 'dhariyale ge may, shriguruche pay', hin: 'पाहुणी आलीस माझ्या घरी', dir: '1', id: '70.2' },
 { eng: 'karunakara din vatsal datta', hin: 'अंबे तुझ्या भेटीसाठी', dir: '1', id: '70.3' },
 { eng: 'man laga mora avadhuta se', hin: 'पाव रेणूके भवभय हरिणी', dir: '1', id: '71.1' },
 { eng: 'ata jau chala amhi pahu chala', hin: 'रूप सुंदर सुंदर', dir: '1', id: '71.2' },
 { eng: 'naman maje gururaya', hin: 'पाव ग तुळजापूर माते', dir: '1', id: '72.1' },
 { eng: 'smara smara ho datt guru bhavatap haru', hin: 'आम्ही चुकलो जरी तरी कांही', dir: '1', id: '72.2' },
 { eng: 'paulele chalati kashim purchi vat', hin: 'मी लेकरू तूं माय रेणुके.', dir: '1', id: '73.1' },
 { eng: 'shirdiwale saibaba, aya hai tere dar pe sawali', hin: 'कृपा दृष्टि पाहे मजला तूं आई', dir: '1', id: '73.2' },
 { eng: 'datt datt datt datt, datt mhana', hin: 'नवरात्रीचा उत्सव आला', dir: '1', id: '74.1' },
 { eng: 'ekachi dhyas lagla mani', hin: 'करुया जय जयकार', dir: '1', id: '75.1' },
 { eng: 'aisa dayalu aisa krupalu', hin: 'अंबे तुझे ग दर्शन घेता', dir: '1', id: '75.2' },
 { eng: 'bhaktan la ladu datta rahile ganagapuri', hin: 'पाहु द्या मला पाहु द्या मला', dir: '1', id: '76.1' },
 { eng: 'chala chala jau shirdila', hin: 'किती अंत पाहसि माते जीव हा भुकेला', dir: '1', id: '76.2' },
 { eng: 'gurudatt digambar bhajo re digambar', hin: 'चला जाऊ या तुळजापुराला', dir: '1', id: '77.1' },
 { eng: 'avaghe garje audumbar', hin: 'शोधू कुठे तुजला भवानी', dir: '1', id: '77.2' },
 { eng: 'kapali chandanacha tila', hin: 'दीन हांक ऐकुनि प्रेम दाटले मनी', dir: '1', id: '78.1' },
 { eng: 'rastyavar he mandir', hin: 'कुलस्वामिनी दूर्गामाता सिंहारूढ बसली', dir: '1', id: '78.2' },
 { eng: 'omkar svarupa sadguru samartha', hin: 'चला जाऊ कोल्हापुरी अंबा दर्शनाला', dir: '1', id: '79.1' },
 { eng: 'haridwar mathura kashi', hin: 'या हो या हो या हो । पर्वणी ही साधु या', dir: '1', id: '80.1' },
 { eng: 'shiradi pandharpur maze', hin: 'अंबे मैय्या पार करो मोरी नैय्या', dir: '1', id: '80.2' },
 { eng: 'divana aapko nahi dhunda', hin: 'भवतारीणी माता जननी', dir: '1', id: '81.1' },
 { eng: 'zhale amhi bahu dhanya re', hin: 'अनादी निर्गुण प्रगटली भवानी (जोगवा)', dir: '1', id: '81.2' },
 { eng: 'datta brahmachari re brahmachari', hin: 'मागतो मोदे भक्तिचा (जोगवा)', dir: '1', id: '82.1' },
 { eng: 'gurujine maj bolne khuntvile', hin: 'अंबे मैय्या अंबे मैय्या मान जा', dir: '1', id: '82.2' },
 { eng: 'kiti sukh aha, kiti sukh he', hin: 'ऐसा प्यार बहा दो मैय्या', dir: '1', id: '83.1' },
 { eng: 'alakh niranjan alakh tu bhaj le', hin: 'तुने मुझे बुलाया शेरा वालिये', dir: '1', id: '83.2' },
 { eng: 'guruvin nahi koni re', hin: 'आयी शेर पे सवार मैय्या ओढे चुनरि', dir: '1', id: '84.1' },
 { eng: 'sadguru yave mam bhajani sadar vhave', hin: 'जय जय हे जगदंबे माता', dir: '1', id: '84.2' },
 { eng: 'gela datt kunya ganva', hin: 'सुनती है मैय्या सबकी पुकार', dir: '1', id: '85.1' },
 { eng: 'gurunamachi odh dattanamachi odh', hin: 'बोला जगदंबे बोला', dir: '1', id: '85.2' },
 { eng: 'sadguru sarikha asta pathirakha', hin: 'भक्तिचा लळा लावूनी', dir: '1', id: '86.1' },
 { eng: 'sadguru vanchoni sampdena soy', hin: 'पाव माते आई जगदंबे', dir: '1', id: '86.2' },
 { eng: 'shripad shrivallabh narhari tari tari majla', hin: 'आदीशक्तीचे कौतुक मोठे', dir: '1', id: '87.1' },
 { eng: 'shridhara guruvara - pav maj pamara', hin: 'मी तुझा भुत्या खरा', dir: '1', id: '87.2' },
 { eng: 'digambara digambara dhavat yesi bhaktasathi', hin: 'उदे उदे ग अंबाबाई - माझी तुळजापूरची आई', dir: '1', id: '88.1' },
 { eng: 'maze punya phala ale', hin: 'भक्तोकों दर्शन दे गई रे', dir: '1', id: '89.1' },
 { eng: 'prabhuvin kon kunacha vali', hin: 'लल्लाटी भंडार', dir: '1', id: '90.1' },
 { eng: 'shripad vallabh digambara namasathi tvara kara', hin: 'करु या उदो उदो उदो अंबाबाईचा', dir: '1', id: '91.1' },
 { eng: 'nighalo gheun dattachi palkhi', hin: 'अंबे तुझ्या दर्शनाची मला झाली घाई', dir: '1', id: '92.1' },
 { eng: 'chala jau ya ganagapurala', hin: 'मैया मेरी ओ मैया मेरी, सुनले तू बिनती हमारी', dir: '1', id: '92.2' },
 { eng: 'bhan harapale dattprabhuchi', hin: 'उदे ग अंबे उदे, उदे ग अंबे उदे', dir: '1', id: '93.1' },
 { eng: 'naka vicharu dev kasa', hin: 'उदो बोला उदो ऽऽ', dir: '1', id: '94.1' },
 { eng: 'brahma vishnu ani maheshvar samori basle', hin: 'काली काली अमावस की रात में', dir: '1', id: '94.2' },
 { eng: 'bhima amarja sangmatiri', hin: 'नऊवारी साडी नेसून....', dir: '1', id: '95.1' },
 { eng: 'datt daya ghan re', hin: 'हळदीवरी कुंकू शोभे अंबाबाईला', dir: '1', id: '95.2' },
 { eng: 'jithe bhaktiche gayan chale', hin: 'बासर वासिनि माझे आई', dir: '1', id: '95.3' },
 { eng: 'bhasma sushobhit komal kaya', hin: 'जय अंबे, जय दुर्गे, माहाकाली', dir: '1', id: '96.1' },
 { eng: 'tin shire saha hat', hin: 'शारदेच्या मंदीरी विणे चा झनकार', dir: '1', id: '96.2' },
 { eng: 'dattasi gain - dattasi pahin', hin: 'भाग्यद लक्ष्मी बारम्मा', dir: '1', id: '97.1' },
 { eng: 'nighalo gheun dindi vitthalachi', hin: 'यहाँ वहाँ जहाँ तहाँ', dir: '1', id: '98.1' },
 { eng: 'mauli mauli rup tuje', hin: 'जागो हे जगदंबे जागो हे ज्वाला', dir: '1', id: '99.1' },
 { eng: 'rukmaichya kanta ata tujach re asra', hin: 'उदो उदो उदो माऊली अंबाबाई', dir: '1', id: '100.1' },
 { eng: 'maj santacha adhar', hin: 'तेरा सहारा अंबे माँ मुझे तेरा सहारा', dir: '1', id: '100.2' },
 { eng: 'dev maje man lage tuje charani', hin: 'मै बालक तु माता शेरावालीये', dir: '1', id: '101.1' },
 { eng: 'pahu dya mala - pahu dya mala', hin: 'हरिवी साडी ग शोमें माझ्या आईला.', dir: '1', id: '102.1' },
 { eng: 'dehachi tijori bhaktichach theva', hin: 'मंगल करती आयी है मैयाँ, मंगल कार्य करेगी मैयाँ,', dir: '1', id: '102.2' },
 { eng: 'vitthal tal vitthal dindi', hin: 'तुमबिन मोरी कौन खबर ले', dir: '1', id: '103.1' },
 { eng: 'chala jauya rammandirala', hin: 'मोहन प्यारे को तुने न जाना रे', dir: '1', id: '103.2' },
 { eng: 'charani vahe chandrabhaga yuge athavis ubha', hin: 'तोरे बन्सी के नाद दिवानी भई', dir: '1', id: '104.1' },
 { eng: 'avaghe garje pandharpur', hin: 'कन्हैया रुतली रे घोंगडी', dir: '1', id: '104.2' },
 { eng: 'kanda raja pandharicha', hin: 'कृष्णा तुला मी ताकीद करते', dir: '1', id: '105.1' },
 { eng: 'dev maza vithu sawala', hin: 'कृष्णा मजकडे पाहू नको', dir: '1', id: '105.2' },
 { eng: 'devachiye dvari ubha kshanbhari', hin: 'घुसळीत होते दारी मी लोणी', dir: '1', id: '106.1' },
 { eng: 'janmo janmi amhi bahu punya kele', hin: 'नेसली ग बाई चंद्रकला ठिपक्याची', dir: '1', id: '106.2' },
 { eng: 'phirtya chaka varti desi', hin: 'मलयगिरीचा चंदन गंधित धुप तुला दाविला', dir: '1', id: '107.1' },
 { eng: 'ali kuthunshi kani tal mrudungachi dhun', hin: 'जाऊ दे रे मला, जाऊ दे रे मला', dir: '1', id: '108.1' },
 { eng: 'yeg yeg vithabai', hin: 'गोधने चारावया जातो सारंगपाणी', dir: '1', id: '108.2' },
 { eng: 'tal bole chipalila', hin: 'असा कसा देवाचा देव बाई ठकडा', dir: '1', id: '109.1' },
 { eng: 'vahe chandrabhaga tuka dang bhajanat', hin: 'वारीयाने कुंडल हाले', dir: '1', id: '109.2' },
 { eng: 'avadine bhave hari nam ghesi', hin: 'किती गोड मुरलीच्या नादाने', dir: '1', id: '110.1' },
 { eng: 'kaya hi pandhari atma ha vitthal avadine bhave hari nam ghesi', hin: 'वाकूनी टाक सडा ग राधे', dir: '1', id: '110.2' },
 { eng: 'udand dekhile, udand aikile', hin: 'कुंज वनाची वाट राधीके कुंज वनाची वाट', dir: '1', id: '111.1' },
 { eng: 'janan kashala dur majla ithch pandharpur', hin: 'डाव्या गुडघ्याने रांगतो', dir: '1', id: '111.2' },
 { eng: 'vitthal-vitthal smare velo vela', hin: 'आला रे बाई बाई आला रे बाई बाई आला रे....', dir: '1', id: '112.1' },
 { eng: 'jay pandurang prabho vithhala', hin: 'मला अडवु नको रे गिरिधारी', dir: '1', id: '112.2' },
 { eng: 'vitthalachya payi vit zali bhagyavant', hin: 'धाका मधला मोहन माझा', dir: '1', id: '113.1' },
 { eng: 'kaivalyacha chandanyala bhukela chakor', hin: 'आला कान्हा मागण्यासी आला', dir: '1', id: '114.1' },
 { eng: 'santachiye ganvi premacha sukal', hin: 'तुझी संगती नाही कामाची ...', dir: '1', id: '114.2' },
 { eng: 'aga pandharichya raya', hin: 'नको झोंबू पदराला', dir: '1', id: '115.1' },
 { eng: 'ba re panduranga kenva bhet desi', hin: 'यशवदे गं बाळ तुझा गं', dir: '1', id: '115.2' },
 { eng: 'sandonya sarv asha sansarachi', hin: 'खाल्ल यशवदे कृष्णानं लोणी...', dir: '1', id: '116.1' },
 { eng: 'jato maghari pandhari natha', hin: 'अरे कान्हा या गवळणी तुला घाबरती', dir: '1', id: '116.2' },
 { eng: 'chala pandharpurala jauya', hin: 'घोंगडीवाला कांबळीवाला', dir: '1', id: '117.1' },
 { eng: 'zhala mahar pandharinath', hin: 'लहान लहान मुले घेऊनी.', dir: '1', id: '117.2' },
 { eng: 'sanga mi kay karu', hin: 'भिती भिती भिती बाइ बाइ भिती', dir: '1', id: '118.1' },
 { eng: 'kanda mula bhaji', hin: 'वाजवितो पावा तो कृष्ण मुरारी', dir: '1', id: '119.1' },
 { eng: 'unch nich kahi nene bhagvant', hin: 'उशीर झाला का परतण्याला', dir: '1', id: '120.1' },
 { eng: 'khel mandiyela valvanti ghai', hin: 'चावट कान्हा भोळी राधा', dir: '1', id: '121.1' },
 { eng: 'vithu maza lekurvala', hin: 'कां ग राधे स्मित हसली', dir: '1', id: '122.1' },
 { eng: 'chandrabhagechya tiri ubha mandiri', hin: 'मुरली तुझी गोड कान्हा', dir: '1', id: '122.2' },
 { eng: 'tukobachi kanta sange sange lokapashi', hin: 'सांग सुदामा हरिचा चेंडू.', dir: '1', id: '123.1' },
 { eng: 'tukobachi amrutvani', hin: 'बंदानो गोविंदा छंददी आनंदा', dir: '1', id: '123.2' },
 { eng: 'ya sukha karane dev vedavala', hin: 'आडवू नका बाया आडवू नका', dir: '1', id: '124.1' },
 { eng: 'chala jau ya pandharpurala', hin: 'बाळ झोक्यामध्ये खेले गं राधा मावशीच्या घरि', dir: '1', id: '124.2' },
 { eng: 'darshan de re dere bhagvanta', hin: 'कधी करितो गं चोरि कधी करि शिरजोरि', dir: '1', id: '125.1' },
 { eng: 'pandharicha vas chandrabhage snan', hin: 'यशोदेचा कान्हा गोकुळचा चोर..', dir: '1', id: '126.1' },
 { eng: 'yete pandharila tujhya sarangadhara', hin: 'आला हो कान्हा आला .......', dir: '1', id: '126.2' },
 { eng: 'pandhari nivasa sakhya panduranga', hin: 'रुतला पायी कांटा या आडवाटा.', dir: '1', id: '127.1' },
 { eng: 'indrayani kathi devachi alandi', hin: 'हरि नाम भजा हो प्रभुनाम', dir: '1', id: '127.2' },
 { eng: 'dharila pandharicha chor', hin: 'सोडूनी गोपिला गोपिला देव मथुरेसी चालला', dir: '1', id: '128.1' },
 { eng: 'amhi bighadlo tumhi bighadana', hin: 'मोहना जरा थांबना थांब रे मारू नको पिचकारी', dir: '1', id: '128.2' },
 { eng: 'vedha vedha re pandhari', hin: 'केशवा माधवा तुझ्या नामात रे गोडवा', dir: '1', id: '129.1' },
 { eng: 'mani nahi bhav mhane deva mala pav re', hin: 'वृंदावनी वेणू वेणू वृंदावनी वेणू ........', dir: '1', id: '129.2' },
 { eng: 'he pandhari nath deva amhi tula smarave', hin: 'ऐसी लागी लगन मीरा हो गई मगन', dir: '1', id: '130.1' },
 { eng: 'tirth vitthal kshetra vitthal', hin: 'आली दही वाली दही घ्या ताजी', dir: '1', id: '131.1' },
 { eng: 'dhanya aji din sant darshanacha', hin: 'चावट कृष्ण राधा भोळी ला', dir: '1', id: '132.1' },
 { eng: 'maze maher pandhari', hin: 'ओ आली पाहा मधुर तान', dir: '1', id: '133.1' },
 { eng: 'santachiye ganvi premacha sukal', hin: 'कुणी सांगा हो कान्हा हिरमुसला.', dir: '1', id: '134.1' },
 { eng: 'ata kothe dhave man', hin: 'कशासाठी येवू देवा तुझ्या मंदिरात', dir: '1', id: '135.1' },
 { eng: 'lahan pan dega deva', hin: 'जय गंगे भगीरथी हर गंगे भागिरथी', dir: '1', id: '135.2' },
 { eng: 'nishtavant bhav bhaktanchya swadharm', hin: 'असा कसा बाई माझा भोळा शंकर.', dir: '1', id: '136.1' },
 { eng: 'maza bhav tuje charani', hin: 'मोहे लागी लटक, गुरु चरनन की', dir: '1', id: '136.2' },
 { eng: 'devachiye dvari ubha kshanbhari', hin: 'श्रीरामचंद्र कृपालु भजमन हरण भवमय दारूणम्', dir: '1', id: '137.1' },
 { eng: 'sakha din vatsal pandhariraya', hin: 'सुंदर ते ध्यान शोभे सिंहासनी', dir: '1', id: '137.2' },
 { eng: 'ek tatva name drudh dhari mana', hin: 'राम गावा राम घ्यावा राम जीविचा विसावा', dir: '1', id: '138.1' },
 { eng: 'dhara balakat bhav', hin: 'बंध विमोचन राम माझा', dir: '1', id: '138.2' },
 { eng: 'ata tari pudhe hachi upadesh', hin: 'कल्याण करी रामराया - जनहित विवरी', dir: '1', id: '138.3' },
 { eng: 'hechi thor bhakti avadte deva', hin: 'हे अंजनीच्या सुता तुला रामाचे वरदान', dir: '1', id: '139.1' },
 { eng: 'kiti pahu tuzha vat', hin: 'माई मोरे नयन बसे रघुवीर', dir: '1', id: '139.2' },
 { eng: 'vratamaji vrat ekadashi pavan', hin: 'भटजी बापू राया भेटोनिया जावे', dir: '1', id: '140.1' },
 { eng: 'kon divas yeil kaisa', hin: 'पायोजी मैने राम रतन धन पायो', dir: '1', id: '140.2' },
 { eng: 'pandharichya loka kiti maru hanka', hin: 'शोधिसी मानवा राऊळी मंदीरी', dir: '1', id: '140.3' },
 { eng: 'ghei ghei maje vache', hin: 'काय तुला अपवि प्रभू मी', dir: '1', id: '141.1' },
 { eng: 'sada maje dola jado tujhi murti', hin: 'जो भजे हरि को सदा', dir: '1', id: '141.2' },
 { eng: 'anik dusre maj nahi ata', hin: 'मैली चादर ओढके कैसे द्वार तिहारे आवू', dir: '1', id: '142.1' },
 { eng: 'abir gulal udhalit rang', hin: 'मन तृप्त झाले आहे तुझ्या दर्शनी', dir: '1', id: '142.2' },
 { eng: 'gananayakaya ganadevataya ganadhyakshaya dhimahi', hin: 'कभी-कभी भगवान को भी, भक्तों से काम पड़े', dir: '1', id: '143.1' },
 { eng: 'vandan tuzla shri ganaraya', hin: 'जय शिव शंकर जय शंकर भोले', dir: '1', id: '144.1' },
 { eng: 'smara ho pratham ganpatila', hin: 'देव पावलाय देव माझा मल्हारी ]', dir: '1', id: '144.2' },
 { eng: 'purn brahma he kaivalyache', hin: 'ऐ मालिक तेरे बंदे हम, ऐसे हो हमारे करम', dir: '1', id: '145.1' },
 { eng: 'bal bhakta lagi tuchi asra', hin: 'कुठे शोधिशी रामेश्वर अन कुठे शोधीसी काशी', dir: '1', id: '146.1' },
 { eng: 'sa re ga ma pa padahani sa', hin: 'जग मे सुंदर है दो नाम', dir: '1', id: '146.2' },
 { eng: 'ganpati chya darshanane dhanya hou ya', hin: 'राम का गुण गान करिये', dir: '1', id: '147.1' },
 { eng: 'tuj magato mi ata', hin: 'वेंकटेश द्वार तेरे आये है', dir: '1', id: '147.2' },
 { eng: 'ganaraj payi man jad jad jad', hin: 'श्री राम ... स्वये श्रीराम प्रभु ऐकती', dir: '1', id: '148.1' },
 { eng: 'vishva shakti vishva rupa', hin: 'तुम्ही हो माता पिता तुम्ही हो', dir: '1', id: '149.1' },
 { eng: 'sukh shantiche jivan javo', hin: 'कभी राम बन के कभी श्याम बनके', dir: '1', id: '149.2' },
 { eng: 'gajanana shri ganaraya adhi vandu', hin: 'कब लोगे हमारि खबरिया ओ बजरंगबली', dir: '1', id: '150.1' },
 { eng: 'tuch sur thava mazsi', hin: 'मल्हारि म्हाळसाकांत', dir: '1', id: '150.2' },
 { eng: 'jay ganaraya jay ganaraya', hin: 'पवमान पवमान जगद प्राणा', dir: '1', id: '151.1' },
 { eng: 'vadalachya uncha lata jau de', hin: 'आल आल रे म्हातार पण आल रे...', dir: '1', id: '152.1' },
 { eng: 'more ghar chalo ganaraj', hin: 'संगीत सत्यनारायण', dir: '1', id: '153.1' },

];

if (typeof module === 'object' && module.exports) {
    module.exports = p1;
}
