var p2 = [
     { eng: 'devi navaratri arati ashwin masi shukla', hin: 'नवरात्र देवी आरती', dir: '2', id: '1' },
     { eng: 'devi aai bhavani tuzya krupene', hin: 'आई भवानी तुझ्या कृपेने', dir: '2', id: '2' },
     { eng: 'devi chalo bulava aya hai', hin: 'चलो बुलावा आया है', dir: '2', id: '3' },
     { eng: 'gajanan shegaon nivasi maharaj mere', hin: 'शेगांव निवासी, महाराज मेरे', dir: '2', id: '4' }, 
     { eng: 'devi kya shan shaan hai tulaja', hin: 'क्या शान है तुलजा भवानी की', dir: '2', id: '5' },
     { eng: 'krushna veda houni nache anand', hin: 'वेडा होऊनी नाचे आनंद', dir: '2', id: '6' },
     { eng: 'krushna savaliya giridhari lal khabar', hin: 'सांवलिया गिरिधारी लाल खबर लेना मेरी', dir: '2', id: '7' },
     { eng: 'devi painjanacha nad naad', hin: 'पैंजनाचा नाद', dir: '2', id: '8' },
     { eng: 'devi dongaravari', hin: 'डोंगरावरी डोंगर ग', dir: '2', id: '9' },
     { eng: 'krushna achyutam keshavam', hin: 'अच्चुतम केशवं कृष्ण दामोदरं', dir: '2', id: '10' },
     { eng: 'ram nadatuni naad nirmito', hin: 'नादातुनी या नाद निर्मितो ', dir: '2', id: '11' },
     { eng: 'devi adimaya ambabai sarya duniyechi', hin: 'आदिमाया अंबाबाई साऱ्या दुनियेची', dir: '2', id: '12' },
     { eng: 'nav swaminche yeta mazya', hin: 'नाव स्वामींचे येता माझ्या', dir: '2', id: '13' },
     { eng: 'devi ashwin mahinya ali khelat', hin: 'अश्वीन महीन्यात आली खेळत खेळत', dir: '2', id: '14' },
     { eng: 'swami bhiu nako mi tuzya pathishi aahe', hin: 'भिऊ नको मी तुझ्या पाठीशी आहे', dir: '2', id: '15' },
     { eng: 'kiti sukh hai', hin: 'किति सुख हे किती', dir: '2', id: '16' }, 
     { eng: 'datta namacha mahima', hin: 'दत्त दत्त नामाचा महिमा', dir: '2', id: '17' },
     { eng: 'har sans saas me sumiran', hin: 'हर सांस मे हो सुमिरन तेरा', dir: '2', id: '18' },
     { eng: 'he dukha dukkha bhanjan', hin: 'हे दुःख भन्जन, मारुती नंदन', dir: '2', id: '19' },
     { eng: 'jalato ha nandadip', hin: 'जळतो हा नंदादीप', dir: '2', id: '20' },
     { eng: 'tari mala jagadambe', hin: 'तारी मला जगदंबे', dir: '2', id: '21' },
     { eng: 'pandurang ale aale', hin: 'पांडुरंग आले आले', dir: '2', id: '22' },
     { eng: 'man ki tarang mar lo', hin: 'मन की तरंग मार लो', dir: '2', id: '23' },
     { eng: 'vithu mauli jagachi', hin: 'विठू माऊली तू माऊली जगाची', dir: '2', id: '24' },
     { eng: 'jyot milate', hin: 'ज्योत से ज्योत जगाते चलो', dir: '2', id: '25' },
     { eng: 'akkalkoti dhyan lagale', hin: 'अक्कलकोटी  ध्यान लागले माझ्या मनाचे', dir: '2', id: '26' },
     { eng: 'akkalkot swaminchi palakhi', hin: 'अक्कलकोट स्वामींची पालखी निघाली', dir: '2', id: '27' },
     //{ eng: '', hin: '', dir: '2', id: '28 },
     //{ eng: '', hin: '', dir: '2', id: '29 },
     //{ eng: '', hin: '', dir: '2', id: '30' },
     //{ eng: '', hin: '', dir: '2', id: '31' },
     //{ eng: '', hin: '', dir: '2', id: '32' },
     //{ eng: '', hin: '', dir: '2', id: '33' },
     //{ eng: '', hin: '', dir: '2', id: '34' },
     //{ eng: '', hin: '', dir: '2', id: '35' },
     //{ eng: '', hin: '', dir: '2', id: '36' },
     //{ eng: '', hin: '', dir: '2', id: '37' },
     //{ eng: '', hin: '', dir: '2', id: '38' },
     //{ eng: '', hin: '', dir: '2', id: '39' },
     //{ eng: '', hin: '', dir: '2', id: '41' },
     //{ eng: '', hin: '', dir: '2', id: '42' },
     //{ eng: '', hin: '', dir: '2', id: '43' },
     //{ eng: '', hin: '', dir: '2', id: '44' },
     //{ eng: '', hin: '', dir: '2', id: '45' },
     //{ eng: '', hin: '', dir: '2', id: '46' },
     //{ eng: '', hin: '', dir: '2', id: '47' },
     //{ eng: '', hin: '', dir: '2', id: '48' },
     //{ eng: '', hin: '', dir: '2', id: '49' },
     //{ eng: '', hin: '', dir: '2', id: '50' },
     //{ eng: '', hin: '', dir: '2', id: '51' },

];

if (typeof module === 'object' && module.exports) {
    module.exports = p2;
}
