name: Index Generator
run-name: Regenerating index


on:
  push:
    branches:
      - main
    paths:
      - 'scripts/*.js'
      - '!scripts/indexdata.js'   # exclude generated file
  workflow_dispatch: {}

permissions:
  contents: write                # ensure the job can push changes

concurrency:
  group: index-generator
  cancel-in-progress: true

jobs:
  update-file:
    runs-on: ubuntu-latest
    # optionally skip runs triggered by the action itself:
    if: ${{ github.actor != 'github-actions[bot]' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Node.js (use an LTS)
        uses: actions/setup-node@v3
        with:
          node-version: '18'     # recommend a currently supported LTS

      - name: Install dependencies
        run: npm install

      - name: Run index generator
        run: node ./scripts/indexgenerator.js

      # Option A: use a safe action to add & commit
      - name: Commit & push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update file with new index data [skip ci]
          add: 'scripts/indexdata.js'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Option B: shell-based safe commit (if you prefer shell)
      # - name: Commit & push (shell)
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add scripts/indexdata.js
      #     if git diff --cached --quiet; then
      #       echo "No changes to commit"
      #       exit 0
      #     fi
      #     git commit -m "Update file with new index data [skip ci]"
      #     git push
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
